[tool.poetry]
name = "pyvectorguidance"
version = "0.0.1"
description = "Vecotr guidance for python"
authors = ["Iftach Naftaly <iftahnaf@proton.me>"]
license = "Apache-2.0"
keywords = ["guidance", "control", "autonomous-systems"]
readme = "README.md"
homepage = "https://github.com/iftahnaf/pyvectorguidance"
repository = "https://github.com/iftahnaf/pyvectorguidance"
include = [
    "LICENSE",
]

packages = [
    { include = "pyvectorguidance", from = "pyvectorguidance" },
]


[tool.poetry.urls]
"Changelog" = "https://github.com/iftahnaf/pyvectorguidance/blob/main/CHANGELOG.md"


[tool.semantic_release]
version_variable = [
    "pyvectorguidance/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]

branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
click = ">=7"
toml = ">=0.10.2"
rich = ">=10.14.0"
typing-extensions = { version = ">=4.5.0", python = "<3.11" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^2.12.1"
flake8 = "^6.0.0"
flake8-annotations = "^3.0.1"
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^2.13.0"
astpretty = "^3.0.0"
python-semantic-release = "^7.33.5"
types-toml = "^0.1.3"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
extra_standard_library = ["pytest", "toml", "click", "typing_extensions"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"