# name: Semantic Release

# on:
#   push:
#     branches:
#       - main

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     concurrency: release
#     permissions:
#       id-token: write
#       contents: write

#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: 0
#         token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}

#     - name: Python Semantic Release
#       uses: python-semantic-release/python-semantic-release@master
#       with:
#         github_token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}

name: Release

on: 
  push:
    branches: 
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/github @semantic-release/commit-analyzer @semantic-release/git @semantic-release/release-notes-generator semantic-release-pypi
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install setuptools
        run: python -m pip install --upgrade setuptools wheel twine
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: npx semantic-release