
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}
          submodules: 'true'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install poetry --upgrade pip
          cd vectorguidance
          mkdir build
          cd build
          sudo apt update && sudo apt install -y libeigen3-dev libgtest-dev cmake
          cmake ..
          make
          make install
          cd ../..
          poetry config virtualenvs.create false
          poetry install

      # Can't use: relekang/python-semantic-release@master because
      # it's running Python 3.7, and Tryceratops requires >=3.8
      - name: Python Semantic Release
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          GH_TOKEN: ${{secrets.SEMANTIC_RELEASE_ACCESS_TOKEN}}
          PyPI_TOKEN: ${{secrets.PYPI_API_TOKEN}}
